#!/bin/bash
#
# Generate xrandr monitor profiles for .xinitrc
# Detects connected monitors and outputs commented configuration lines
#

echo "# ============================================"
echo "# MONITOR CONFIGURATION (generated by xrandr)"
echo "# Uncomment the profile that matches your setup"
echo "# ============================================"
echo ""

# Check if xrandr is available
if ! command -v xrandr &>/dev/null; then
    echo "# xrandr not installed - install with: sudo pacman -S xorg-xrandr"
    exit 1
fi

# Get connected monitors and their modes
echo "# Available monitors detected:"
MONITORS=$(xrandr --query 2>/dev/null | grep " connected" | cut -d' ' -f1)

if [[ -z "$MONITORS" ]]; then
    echo "# No displays detected (X server may not be running)"
    echo "# Run this script after starting X or use: xrandr --query"
    echo ""
    echo "# Example configurations:"
    echo ""
    echo "# --- Single Monitor (1080p 60Hz) ---"
    echo "# xrandr --output HDMI-1 --mode 1920x1080 --rate 60"
    echo ""
    echo "# --- Single Monitor (1440p 144Hz) ---"
    echo "# xrandr --output DP-1 --mode 2560x1440 --rate 144"
    echo ""
    echo "# --- Single Monitor (4K 60Hz) ---"
    echo "# xrandr --output DP-1 --mode 3840x2160 --rate 60"
    echo ""
    echo "# --- Dual Monitor (extend right) ---"
    echo "# xrandr --output DP-1 --mode 2560x1440 --rate 144 --primary \\"
    echo "#        --output HDMI-1 --mode 1920x1080 --rate 60 --right-of DP-1"
    echo ""
    echo "# --- Dual Monitor (mirror) ---"
    echo "# xrandr --output DP-1 --mode 1920x1080 --rate 60 --primary \\"
    echo "#        --output HDMI-1 --mode 1920x1080 --rate 60 --same-as DP-1"
    exit 0
fi

for mon in $MONITORS; do
    echo "# $mon:"
done
echo ""

# Parse xrandr output to get resolutions and refresh rates
echo "# --- DETECTED CONFIGURATIONS ---"
echo ""

for mon in $MONITORS; do
    echo "# Monitor: $mon"
    
    # Get all modes for this monitor
    IN_MONITOR=0
    xrandr --query 2>/dev/null | while IFS= read -r line; do
        if echo "$line" | grep -q "^$mon connected"; then
            IN_MONITOR=1
            # Check if primary
            if echo "$line" | grep -q "primary"; then
                echo "#   (Primary display)"
            fi
        elif echo "$line" | grep -q " connected\| disconnected"; then
            IN_MONITOR=0
        elif [[ $IN_MONITOR -eq 1 ]] && echo "$line" | grep -qE "^\s+[0-9]+x[0-9]+"; then
            # Parse resolution and refresh rates
            RES=$(echo "$line" | awk '{print $1}')
            # Get refresh rates (all numbers after resolution)
            RATES=$(echo "$line" | grep -oE '[0-9]+\.[0-9]+' | head -5)
            
            for rate in $RATES; do
                # Round refresh rate
                RATE_INT=$(echo "$rate" | cut -d'.' -f1)
                # Check if this is the current mode (marked with *)
                if echo "$line" | grep -q "${rate}\*"; then
                    echo "#   ${RES} @ ${RATE_INT}Hz (current)"
                else
                    echo "#   ${RES} @ ${RATE_INT}Hz"
                fi
            done
        fi
    done
    echo ""
done

echo "# --- READY-TO-USE PROFILES ---"
echo ""

# Generate actual xrandr commands for common configurations
MONITOR_ARRAY=($MONITORS)
FIRST_MON="${MONITOR_ARRAY[0]}"

echo "# Single monitor - auto (recommended for laptops)"
echo "# xrandr --output $FIRST_MON --auto --primary"
echo ""

# Get the highest resolution for the first monitor
BEST_MODE=$(xrandr --query 2>/dev/null | grep -A1 "^$FIRST_MON connected" | tail -1 | awk '{print $1}')
BEST_RATE=$(xrandr --query 2>/dev/null | grep -A1 "^$FIRST_MON connected" | tail -1 | grep -oE '[0-9]+\.[0-9]+' | head -1 | cut -d'.' -f1)

if [[ -n "$BEST_MODE" ]]; then
    echo "# Single monitor - best detected mode"
    echo "# xrandr --output $FIRST_MON --mode $BEST_MODE --rate ${BEST_RATE:-60} --primary"
    echo ""
fi

# Common resolutions
echo "# Common single monitor profiles:"
echo "# xrandr --output $FIRST_MON --mode 1920x1080 --rate 60 --primary"
echo "# xrandr --output $FIRST_MON --mode 1920x1080 --rate 144 --primary"
echo "# xrandr --output $FIRST_MON --mode 2560x1440 --rate 60 --primary"
echo "# xrandr --output $FIRST_MON --mode 2560x1440 --rate 144 --primary"
echo "# xrandr --output $FIRST_MON --mode 2560x1440 --rate 165 --primary"
echo "# xrandr --output $FIRST_MON --mode 3840x2160 --rate 60 --primary"
echo "# xrandr --output $FIRST_MON --mode 3840x2160 --rate 120 --primary"
echo ""

# Multi-monitor setup if more than one monitor
if [[ ${#MONITOR_ARRAY[@]} -gt 1 ]]; then
    SECOND_MON="${MONITOR_ARRAY[1]}"
    
    echo "# Dual monitor - extend right"
    echo "# xrandr --output $FIRST_MON --auto --primary \\"
    echo "#        --output $SECOND_MON --auto --right-of $FIRST_MON"
    echo ""
    
    echo "# Dual monitor - extend left"
    echo "# xrandr --output $FIRST_MON --auto --primary \\"
    echo "#        --output $SECOND_MON --auto --left-of $FIRST_MON"
    echo ""
    
    echo "# Dual monitor - extend above"
    echo "# xrandr --output $FIRST_MON --auto --primary \\"
    echo "#        --output $SECOND_MON --auto --above $FIRST_MON"
    echo ""
    
    echo "# Dual monitor - mirror (same content)"
    echo "# xrandr --output $FIRST_MON --auto --primary \\"
    echo "#        --output $SECOND_MON --auto --same-as $FIRST_MON"
    echo ""
fi

# Turn off other monitors
echo "# Turn off a specific monitor"
for mon in $MONITORS; do
    echo "# xrandr --output $mon --off"
done
echo ""

echo "# ============================================"
echo "# Copy desired profile to your ~/.xinitrc"
echo "# Place BEFORE 'exec dwm' line"
echo "# ============================================"
